import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { funcionariosRoutes } from "./funcionarios.routes.js";
import { servicosRoutes } from "./servicos.routes.js";
import { veiculosRoutes } from "./veiculos.routes.js";
import { clienteRoutes } from "./clientes.routes.js";
import { agendamentoRoutes } from "./agendamentos.routes.js";
import { ordemServicoRoutes } from "./ordens_servico.routes.js";
import { financeiroRoutes } from "./financeiro.routes.js";
import { expedienteRoutes } from "./expediente.routes.js";
import { datasBloqueadasRoutes } from "./datas-bloqueadas.routes.js";
import { relatoriosRoutes } from "./relatorios.routes.js";
import { notificacoesRoutes } from "./notificacoes.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { chatbotRoutes } from "../chatbot/chatbot.routes.js";

export const routes = Router();

routes.use("/auth", authRoutes);
routes.use("/funcionarios", funcionariosRoutes);
routes.use("/servicos", servicosRoutes);
routes.use("/veiculos", veiculosRoutes);
routes.use("/clientes", clienteRoutes);
routes.use("/agendamentos", agendamentoRoutes);
routes.use("/ordens-servico", ordemServicoRoutes);
routes.use("/financeiro", financeiroRoutes);
routes.use("/expediente", expedienteRoutes);
routes.use("/datas-bloqueadas", datasBloqueadasRoutes);
routes.use("/relatorios", relatoriosRoutes);
routes.use("/notificacoes", notificacoesRoutes);
routes.use("/dashboard", dashboardRoutes);
routes.use("/chatbot", chatbotRoutes);
